### ISSUE TITLE
Feature Request: Be able to put in data to auto calculate?

### ISSUE THREAD

**Issue by NNickey** [mrgriscom/minesweepr#14]
Such as a left click adds one, and a right click sets 0?
Might be easy to do, but meh.

**Comment by jongyon7192p** [comment]
Yes! It would be so much help! It's especially for starting formations where calculating the probability gets incredibly complicated. If people could remember these formations by their solutions, it would make custom density boards more fun to play, instead of starting out by flailing around and hoping to get a good seed...

**Comment by mrgriscom** [comment]
done

http://mrgris.com/projects/minesweepr/demo/analyzer/
